# Generated by Django 4.2.11 on 2024-04-25 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlbumInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=100)),
                ('duration', models.PositiveIntegerField()),
                ('songamount', models.PositiveIntegerField()),
                ('year', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'AlbumInfo',
            },
        ),
        migrations.CreateModel(
            name='AuthorInfo',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('img', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'AuthorInfo',
            },
        ),
        migrations.CreateModel(
            name='SongInfo',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('img', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=100)),
                ('authormig', models.CharField(max_length=100)),
                ('link', models.CharField(max_length=200)),
                ('duration', models.PositiveIntegerField()),
                ('album', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mods.albuminfo')),
                ('authorId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mods.authorinfo')),
            ],
            options={
                'verbose_name': 'SongInfo',
            },
        ),
        migrations.AddField(
            model_name='albuminfo',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mods.authorinfo'),
        ),
    ]
