# Generated by Django 4.2.11 on 2024-04-25 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mods', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='songinfo',
            old_name='authormig',
            new_name='author',
        ),
    ]
