# Generated by Django 4.2.11 on 2024-04-25 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mods', '0002_rename_authormig_songinfo_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='albuminfo',
            name='authorId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mods.authorinfo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='albuminfo',
            name='author',
            field=models.CharField(max_length=100),
        ),
    ]
