# Generated by Django 4.2.11 on 2024-04-25 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mods', '0003_albuminfo_authorid_alter_albuminfo_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='albuminfo',
            name='authorId',
        ),
    ]
