# Generated by Django 4.2.11 on 2024-04-25 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mods', '0004_remove_albuminfo_authorid'),
    ]

    operations = [
        migrations.AddField(
            model_name='albuminfo',
            name='authord',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.CASCADE, to='mods.authorinfo'),
            preserve_default=False,
        ),
    ]
