# Generated by Django 5.0.3 on 2024-04-24 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_songinfo_album'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorInfo',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('img', models.CharField(max_length=200)),
                ('songamount', models.PositiveIntegerField()),
                ('listeningCount', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'AuthorInfo',
            },
        ),
        migrations.AlterField(
            model_name='albuminfo',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.authorinfo'),
        ),
    ]
