# Generated by Django 5.0.3 on 2024-04-24 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_authorinfo_alter_albuminfo_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songinfo',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.authorinfo'),
        ),
    ]
